package com.demo.shipping;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private char shippingType;

	private Integer zipCode;

	public Order() {
	}

	public char getShippingType() {
		return this.shippingType;
	}

	public void setShippingType(char shippingType) {
		this.shippingType = shippingType;
	}

	public java.lang.Integer getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.Integer zipCode) {
		this.zipCode = zipCode;
	}

	public Order(char shippingType, java.lang.Integer zipCode) {
		this.shippingType = shippingType;
		this.zipCode = zipCode;
	}

}