package com.demo.shipping;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class ShippingMethod implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.Boolean valid;

	private java.lang.String reason;

	public ShippingMethod() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Boolean getValid() {
		return this.valid;
	}

	public void setValid(java.lang.Boolean valid) {
		this.valid = valid;
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public ShippingMethod(java.lang.String name, java.lang.Boolean valid,
			java.lang.String reason) {
		this.name = name;
		this.valid = valid;
		this.reason = reason;
	}

}